### ISSUE TITLE
Participant Authentication

### ISSUE THREAD

**Issue by rschlaefli** [uzh-bf/klicker-uzh-legacy#220]
- [x] Basic authentication with username/password
- [x] AAI-based authentication with a redirect to the join page
- [x] Ensure that only aggregated data is stored on finishing a session
- [x] Ensure that responses are properly pruned from the cache
- [x] Notify the participant that a session is "secret", i.e., that nothing identifying is stored
- [x] Display an error if a participant tries to respond a second time
- [x] Implement a "complete" storage mode where responses are stored in detail
